### ISSUE TITLE
New article - How to setup the Veil Wallet (Linux)

### ISSUE THREAD

**Issue by codeofalltrades** [Veil-Project/Veil-Marketing#3]
### Requirements 
- Step by step guide
 - GUI wallet only
 - Downloading the wallet
 - Downloading the snapshot
 - Applying the snapshot
 - Getting a basecoin address.
 
 ### Bonus
 - Youtube Video
 -  Cross posted to multiple blogs/sites.

### Bounty
1000 Veil

**Comment by seanPhill** [comment]
@ohcee I'm just looking for where you posted your sv... address for the bounty payment. I remember seeing it, but can't seem to find it right now. I think right here would be a good verifiable place to confirm it.

**Comment by ohcee** [comment]
Here it is sv1qqpy56fkfmkffp44q8tjx6scldglaf5qqkwsv3lzd440z9vh6d8y9hcpqts3u7xpwt92gxsyr0n42c228n6j5cczzvrget8hhzyfrq7qydv05qqqr7s9z5

**Comment by seanPhill** [comment]
Closing this now, as the bounty has been paid *and* the guide has been published.
